---
proxy-providers:
  ID:
    type: file
    path: "./proxy_provider/Akun-ID.yaml"
    health-check:
      enable: true
      url: https://cp.cloudflare.com/generate_204
      interval: 180
  SG:
    type: file
    path: "./proxy_provider/Akun-SG.yaml"
    health-check:
      enable: true
      url: https://cp.cloudflare.com/generate_204
      interval: 180
  WORLD:
    type: file
    path: "./proxy_provider/Akun-WORLD.yaml"
    health-check:
      enable: true
      url: https://cp.cloudflare.com/generate_204
      interval: 180
proxy-groups:
- name: Prioritas Umum
  type: select
  use:
  - ID
  - SG
  - WORLD
  proxies:
  - Direct Multi-WAN
- name: Prioritas ID
  type: select
  use:
  - ID
- name: Prioritas SG
  type: select
  use:
  - SG
- name: Prioritas WORLD
  type: select
  use:
  - WORLD
- name: Prioritas Youtube
  type: select
  use:
  - ID
  - SG
  - WORLD
  proxies:
  - Direct Multi-WAN
- name: Prioritas GAME
  type: select
  use:
  - ID
  - SG
  - WORLD
- name: Koneksi Direct
  type: select
  proxies:
  - Direct Multi-WAN
  - Jalur ID
  - Jalur SG
- name: Direct Multi-WAN
  type: select
  proxies:
  - Direct WAN A
  - Direct WAN B
- name: Direct WAN A
  type: select
  interface-name: INTERFACE-WAN-A
  proxies:
  - DIRECT
- name: Direct WAN B
  type: select
  interface-name: INTERFACE-WAN-B
  proxies:
  - DIRECT
- name: Koneksi PortGames
  type: select
  proxies:
  - Jalur GAME
  - Koneksi Direct
  - Direct WAN A
  - Direct WAN B
- name: Koneksi Gaming
  type: select
  proxies:
  - Jalur GAME
  - Koneksi Direct
  - Direct WAN A
  - Direct WAN B
- name: Koneksi Ads
  type: select
  proxies:
  - REJECT
  - Jalur SG
  - Jalur ID
  - Jalur WORLD
- name: Koneksi NSFW
  type: select
  proxies:
  - REJECT
  - Jalur SG
  - Jalur ID
  - Jalur WORLD
- name: Koneksi Umum
  type: fallback
  lazy: false
  proxies:
  - Prioritas Umum
  - Jalur SG
  - Jalur ID
  - Jalur WORLD
  - Direct Multi-WAN
  url: https://cp.cloudflare.com/generate_204
  interval: 90
- name: Koneksi Indo
  type: fallback
  lazy: false
  proxies:
  - Jalur ID
  - Jalur SG
  - Koneksi Direct
  url: https://cp.cloudflare.com/generate_204
  interval: 90
- name: Koneksi Youtube
  type: fallback
  lazy: false
  proxies:
  - Prioritas Youtube
  - Jalur SG
  - Jalur ID
  - Jalur WORLD
  - Direct Multi-WAN
  url: https://cp.cloudflare.com/generate_204
  interval: 90
- name: Koneksi Streaming
  type: fallback
  lazy: false
  proxies:
  - Jalur SG
  - Jalur ID
  - Jalur WORLD
  - Direct Multi-WAN
  url: https://cp.cloudflare.com/generate_204
  interval: 90
- name: Koneksi Sosmed
  type: fallback
  lazy: false
  proxies:
  - Jalur ID
  - Jalur SG
  - Jalur WORLD
  - Direct Multi-WAN
  url: https://cp.cloudflare.com/generate_204
  interval: 90
- name: Jalur ID
  type: fallback
  lazy: false
  proxies:
  - Prioritas ID
  use:
  - ID
  url: https://cp.cloudflare.com/generate_204
  interval: 360
- name: Jalur SG
  type: fallback
  lazy: false
  proxies:
  - Prioritas SG
  use:
  - SG
  url: https://cp.cloudflare.com/generate_204
  interval: 360
- name: Jalur WORLD
  type: fallback
  lazy: false
  proxies:
  - Prioritas WORLD
  use:
  - WORLD
  url: https://cp.cloudflare.com/generate_204
  interval: 360
- name: Jalur GAME
  type: fallback
  lazy: false
  proxies:
  - Prioritas GAME
  - Jalur ID
  - Jalur SG
  url: https://cp.cloudflare.com/generate_204
  interval: 600
- name: Speedtest
  type: select
  use:
  - ID
  - SG
  - WORLD
  proxies:
  - Direct Multi-WAN
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7895
geodata-mode: true
geodata-loader: memconservative
tcp-concurrent: true
find-process-mode: 'off'
allow-lan: true
bind-address: "*"
mode: rule
log-level: silent
ipv6: true
unified-delay: false
global-client-fingerprint: chrome
keep-alive-interval: 15
external-controller: 0.0.0.0:9090
external-ui: "/usr/share/openclash/ui"
secret: IPTUNNELS
profile:
  store-selected: true
  store-fake-ip: false
sniffer:
  enable: true
  parse-pure-ip: true
  force-domain:
  - "+.netflix.com"
  - "+.nflxvideo.net"
  - "+.amazonaws.com"
  - "+.media.dssott.com"
  skip-domain:
  - "+.apple.com"
  - Mijia Cloud
  - dlg.io.mi.com
  sniff:
    TLS:
      ports:
      - 443
      - 2053
      - 2083
      - 2087
      - 2096
      - 8443
    HTTP:
      ports:
      - 80
      - 8080
      - 8880
      - 2052
      - 2082
      - 2086
      - 2095
      override-destination: true
dns:
  enable: true
  listen: 0.0.0.0:7874
  ipv6: true
  prefer-h3: false
  use-hosts: true
  default-nameserver:
  - 9.9.9.9#INTERFACE-WAN
  - 1.1.1.1#INTERFACE-WAN
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  nameserver:
  - 9.9.9.9#Jalur ID
  - 1.1.1.1#Jalur SG
  - 8.8.8.8#Jalur WORLD
  fallback:
  - 149.112.112.112:53#Jalur ID
  - 1.0.0.1:53#Jalur SG
  - 8.8.4.4:53#Jalur WORLD
  nameserver-policy:
    geosite:oisd-full,d3ward,rule-doh,rule-malicious: rcode://success
    RULE-SET:rule_direct: 208.67.220.220#Koneksi Direct
    geosite:google-ads: 208.67.222.222#Koneksi Ads
    geosite:oisd-nsfw,category-porn: 208.67.220.220#Koneksi NSFW
    geosite:rule-speedtest: 8.8.4.4#Speedtest
    geosite:rule-umum: 9.9.9.9#Koneksi Umum
    geosite:rule-indo,bank-id: 149.112.112.112#Koneksi Indo
    geosite:youtube: 8.8.8.8#Koneksi Youtube
    geosite:rule-streaming,videoconference: 1.1.1.1#Koneksi Streaming
    geosite:rule-sosmed: 1.0.0.1#Koneksi Sosmed
    geosite:rule-gaming: 8.8.8.8#Koneksi Gaming
    rule-set:rule_umum: 9.9.9.9#Koneksi Umum
  proxy-server-nameserver:
  - 208.67.222.222#INTERFACE-WAN
  - 208.67.220.220#INTERFACE-WAN
  fake-ip-filter:
  - "*.lan"
  - "*.localdomain"
  - "*.example"
  - "*.invalid"
  - "*.localhost"
  - "*.test"
  - "*.local"
  - "*.home.arpa"
  - time.*.com
  - time.*.gov
  - time.*.edu.cn
  - time.*.apple.com
  - time-ios.apple.com
  - time1.*.com
  - time2.*.com
  - time3.*.com
  - time4.*.com
  - time5.*.com
  - time6.*.com
  - time7.*.com
  - ntp.*.com
  - ntp1.*.com
  - ntp2.*.com
  - ntp3.*.com
  - ntp4.*.com
  - ntp5.*.com
  - ntp6.*.com
  - ntp7.*.com
  - "*.time.edu.cn"
  - "*.ntp.org.cn"
  - "+.pool.ntp.org"
  - time1.cloud.tencent.com
  - music.163.com
  - "*.music.163.com"
  - "*.126.net"
  - musicapi.taihe.com
  - music.taihe.com
  - songsearch.kugou.com
  - trackercdn.kugou.com
  - "*.kuwo.cn"
  - api-jooxtt.sanook.com
  - api.joox.com
  - joox.com
  - y.qq.com
  - "*.y.qq.com"
  - streamoc.music.tc.qq.com
  - mobileoc.music.tc.qq.com
  - isure.stream.qqmusic.qq.com
  - dl.stream.qqmusic.qq.com
  - aqqmusic.tc.qq.com
  - amobile.music.tc.qq.com
  - "*.xiami.com"
  - "*.music.migu.cn"
  - music.migu.cn
  - "+.msftconnecttest.com"
  - "+.msftncsi.com"
  - msftconnecttest.com
  - msftncsi.com
  - localhost.ptlogin2.qq.com
  - localhost.sec.qq.com
  - "+.srv.nintendo.net"
  - "*.n.n.srv.nintendo.net"
  - "+.stun.playstation.net"
  - xbox.*.*.microsoft.com
  - "*.*.xboxlive.com"
  - xbox.*.microsoft.com
  - xnotify.xboxlive.com
  - "+.battlenet.com.cn"
  - "+.wotgame.cn"
  - "+.wggames.cn"
  - "+.wowsgame.cn"
  - "+.wargaming.net"
  - proxy.golang.org
  - stun.*.*
  - stun.*.*.*
  - "+.stun.*.*"
  - "+.stun.*.*.*"
  - "+.stun.*.*.*.*"
  - "+.stun.*.*.*.*.*"
  - heartbeat.belkin.com
  - "*.linksys.com"
  - "*.linksyssmartwifi.com"
  - "*.router.asus.com"
  - mesu.apple.com
  - swscan.apple.com
  - swquery.apple.com
  - swdownload.apple.com
  - swcdn.apple.com
  - swdist.apple.com
  - lens.l.google.com
  - stun.l.google.com
  - "+.nflxvideo.net"
  - "*.square-enix.com"
  - "*.finalfantasyxiv.com"
  - "*.ffxiv.com"
  - "*.ff14.sdo.com"
  - ff.dorado.sdo.com
  - "*.mcdn.bilivideo.cn"
  - "+.media.dssott.com"
  - shark007.net
  - "+.qq.com"
  - "+.tencent.com"
  - na.b.g-tun.com
  - Mijia Cloud
  - "+.cmbchina.com"
  - "+.cmbimg.com"
  - local.adguard.org
  - "+.sandai.net"
  - "+.n0808.com"
rules:
- GEOIP,private,DIRECT,no-resolve
- RULE-SET,rule_direct,Koneksi Direct
- GEOSITE,rule-malicious,REJECT
- GEOSITE,google-ads,Koneksi Ads
- GEOSITE,oisd-full,REJECT
- GEOSITE,d3ward,REJECT
- GEOSITE,oisd-nsfw,Koneksi NSFW
- GEOSITE,category-porn,Koneksi NSFW
- GEOSITE,rule-speedtest,Speedtest
- DST-PORT,8080,Speedtest
- DST-PORT,22,Speedtest
- GEOSITE,rule-umum,Koneksi Umum
- OR,((GEOSITE,rule-umum),(DST-PORT,9993/29994/40775/42069/43215)),Koneksi Umum
- GEOSITE,bank-id,Koneksi Indo
- GEOSITE,rule-indo,Koneksi Indo
- GEOIP,netflix,Koneksi Indo
- GEOSITE,youtube,Koneksi Youtube
- GEOSITE,rule-streaming,Koneksi Streaming
- GEOIP,twitter,Koneksi Sosmed
- GEOSITE,rule-sosmed,Koneksi Sosmed
- GEOIP,facebook,Koneksi Sosmed
- GEOIP,telegram,Koneksi Sosmed
- GEOSITE,videoconference,Koneksi Streaming
- DST-PORT,4070,Koneksi Indo,tcp
- DST-PORT,4070,Koneksi Indo,udp
- OR,((DST-PORT,6568/7070),(DOMAIN-SUFFIX,net.anydesk.com)),Koneksi Streaming
- AND,((DST-PORT,5938),(DOMAIN-SUFFIX,teamviewer.com)),Koneksi Streaming
- AND,((DST-PORT,21115-21119),(NETWORK,TCP)),Koneksi Streaming
- AND,((DST-PORT,21116),(NETWORK,UDP)),Koneksi Streaming
- DST-PORT,3478-3497/8801-8810/16384-16387/1853/8200/5004/9000/5090-5091/5349/10000/19302-19309/5938/5060-5061/500/4500,Koneksi
  Streaming
- DST-PORT,5000-5221/5224-5227/5229-5241/5243-5287/5289-5352/5354-5509/5517/5520-5529/5551-5559/5601-5700/8443/9000-9010/9443/10003/30000-30300,Koneksi
  PortGames,tcp
- DST-PORT,5517-5529/5551-5559/5601-5700/8001/8130/8443/9000-9010/9120/9992/10003/30000-30300,Koneksi
  PortGames,udp
- DST-PORT,6006/6008/6674/7006-7008/7889/8001-8012/9006/9137/10000-10012/11000-11019/12006/12008/13006/15006/20561/39003/39006/39698/39779/39800,Koneksi
  PortGames,tcp
- DST-PORT,6006/6008/6674/7006-7008/7889/8008/8001-8012/8130/8443/9008/9120/10000-10015/10100/11000-11019/12008/13008,Koneksi
  PortGames,udp
- DST-PORT,8085-8088/10012/14000/15692/17000/17500/18081/20000-20002/20371,Koneksi
  PortGames,tcp
- DST-PORT,7086-7995/8011-8013/8700/9030-9031/10013/10019/10039/10096/10491/10612/11455/12235/13748/13894/13972/17000/17500/20000-20002/12070-12460/41182-41192,Koneksi
  PortGames,udp
- DST-PORT,8013/8085/10000-10019/18082/20000/50000/65010/65050,Koneksi PortGames,tcp
- DST-PORT,7500-7995/8700/9030/10010-10019/20000-20001,Koneksi PortGames,udp
- DST-PORT,8013/10000-10001/18082/20000-20001/20166/31003/33445/50000,Koneksi PortGames,tcp
- DST-PORT,5008/8011/8700/10000/14050/14080/17000,Koneksi PortGames,udp
- DST-PORT,5055-5058,Koneksi PortGames,udp
- DST-PORT,16100/27015/27036,Koneksi PortGames,tcp
- DST-PORT,27015/27031-27036,Koneksi PortGames,udp
- DST-PORT,42472,Koneksi PortGames,tcp
- DST-PORT,42472/22101-22102,Koneksi PortGames,udp
- DST-PORT,23301,Koneksi PortGames,tcp
- DST-PORT,23301,Koneksi PortGames,udp
- DST-PORT,9330-9340,Koneksi PortGames,tcp
- DST-PORT,9330-9340,Koneksi PortGames,udp
- DST-PORT,2080-2099,Koneksi PortGames,tcp
- DST-PORT,5100,Koneksi PortGames,udp
- DST-PORT,9100-9200/8230-8250/8110-8120/27000-28998,Koneksi PortGames,tcp
- DST-PORT,27000-28998/39000,Koneksi PortGames,udp
- DST-PORT,7770-7790,Koneksi PortGames,tcp
- DST-PORT,16300-16350,Koneksi PortGames,udp
- DST-PORT,44590-44610,Koneksi PortGames,tcp
- DST-PORT,40000-40010,Koneksi PortGames,udp
- DST-PORT,10500-10515,Koneksi PortGames,tcp
- DST-PORT,60970-60980,Koneksi PortGames,udp
- DST-PORT,27015-27030/27036-27037,Koneksi PortGames,tcp
- DST-PORT,4380/27000-27031/27036,Koneksi PortGames,udp
- DST-PORT,14422,Koneksi PortGames
- DST-PORT,16999,Koneksi PortGames
- DST-PORT,8013/8888,Koneksi PortGames
- DST-PORT,30031,Koneksi PortGames,tcp
- DST-PORT,8000/30104,Koneksi PortGames,udp
- DST-PORT,39190-39200/49001-49190,Koneksi PortGames,tcp
- DST-PORT,40000-40010,Koneksi PortGames,udp
- DST-PORT,14009/40005,Koneksi PortGames
- DST-PORT,9339,Koneksi PortGames,tcp
- DST-PORT,2099/8088/8393-8400,Koneksi PortGames,tcp
- DST-PORT,7000-8000/8180-8181/8088/27016-27024/54000-54012,Koneksi PortGames,udp
- DST-PORT,5692/8085/8500/10000/10082/20000/25000/29134/31003,Koneksi PortGames,tcp
- DST-PORT,5010/6650/8011/8700/20000/25000/29134/30000,Koneksi PortGames,udp
- DST-PORT,30100,Koneksi PortGames,udp
- AND,((NOT,((RULE-SET,rule_umum))),(NETWORK,TCP)),Koneksi PortGames
- AND,((NOT,((RULE-SET,rule_umum))),(NETWORK,UDP)),Koneksi PortGames
- GEOSITE,rule-gaming,Koneksi Gaming
- GEOIP,id,Koneksi Indo
- RULE-SET,rule_umum,Koneksi Umum
rule-providers:
  rule_direct:
    type: file
    behavior: classical
    path: "./rule_provider/rule_direct.yaml"
  rule_umum:
    type: file
    behavior: classical
    path: "./rule_provider/rule_umum.yaml"
tun:
  enable: true
  stack: system
  device: utun
  auto-route: false
  auto-detect-interface: false
  dns-hijack:
  - tcp://any:53
authentication:
- Clash:MbRrg6zM